name: Build Android APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: تثبيت Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تثبيت متطلبات النظام
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev

      - name: تثبيت Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install "Cython==0.29.37"

      - name: بناء APK
        run: |
          buildozer android debug

      - name: حفظ APK
        uses: actions/upload-artifact@v4
        with:
          name: FIFA-Auction-APK
          path: bin/*.apk
